"""Job entity."""

from typing import Optional

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from .base import BaseModel


class Job(BaseModel):
    __tablename__ = "jobs"

    task_id = Column(Integer, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(120), nullable=False)
    start_time = Column(String(5), nullable=False)  # HH:mm
    end_time = Column(String(5), nullable=False)
    date_baseline = Column(String(20), nullable=False, default="current_day")
    schedule_type = Column(String(50), nullable=False)
    cron_expression = Column(String(120), nullable=True)
    weekdays = Column(Text, nullable=True)
    execution_time = Column(String(5), nullable=True)  # HH:mm，作业实际触发时间（默认与 start_time 一致）
    offset_minutes = Column(Integer, default=0, nullable=False)
    interval_enabled = Column(Boolean, default=False, nullable=False)
    interval_minutes = Column(Integer, nullable=True)
    window_start = Column(String(5), nullable=False, default="00:00")
    window_end = Column(String(5), nullable=False, default="24:00")
    disk_alert_enabled = Column(Boolean, default=False, nullable=False)
    disk_alert_threshold_bytes = Column(Integer, default=104857600, nullable=False)
    max_retry = Column(Integer, default=1, nullable=False)
    retry_interval_sec = Column(Integer, default=300, nullable=False)
    is_enabled = Column(Boolean, default=True, nullable=False)
    description = Column(Text, nullable=True)
    last_run_at = Column(DateTime, nullable=True)
    next_run_at = Column(DateTime, nullable=True)
    github_deploy_enabled = Column(Boolean, default=False, nullable=False)
    github_config_id = Column(Integer, ForeignKey("github_configs.id", ondelete="SET NULL"), nullable=True)
    html_backup_enabled = Column(Boolean, default=False, nullable=False)
    html_backup_path = Column(Text, nullable=True)
    html_backup_filename_template = Column(Text, nullable=True)
    html_backup_filename_date_offset_days = Column(Integer, default=0, nullable=False)
    github_filename_template = Column(Text, nullable=True)
    days_offset = Column(Integer, default=0, nullable=False)
    display_order = Column(Integer, default=0, nullable=False)
    message_stats_enabled = Column(Boolean, default=False, nullable=False)
    message_stats_formats = Column(Text, nullable=True)
    message_stats_path = Column(Text, nullable=True)
    message_stats_filename_template = Column(Text, nullable=True)
    message_stats_filename_date_offset_days = Column(Integer, default=0, nullable=False)
    message_stats_github_enabled = Column(Boolean, default=False, nullable=False)
    message_stats_github_config_id = Column(Integer, ForeignKey("github_configs.id", ondelete="SET NULL"), nullable=True)
    message_stats_github_filename_template = Column(Text, nullable=True)
    message_stats_github_filename_date_offset_days = Column(Integer, default=0, nullable=False)
    message_stats_github_root = Column(Text, nullable=True)
    chatlog_backup_enabled = Column(Boolean, nullable=True)
    chatlog_backup_path = Column(Text, nullable=True)
    chatlog_backup_formats = Column(Text, nullable=True)
    chatlog_backup_filename_template = Column(Text, nullable=True)
    chatlog_backup_filename_date_offset_days = Column(Integer, default=0, nullable=False)
    model_output_backup_enabled = Column(Boolean, default=False, nullable=False)
    model_output_path = Column(Text, nullable=True)
    model_output_formats = Column("model_output_format", Text, nullable=True)
    model_output_filename_template = Column(Text, nullable=True)
    model_output_filename_date_offset_days = Column(Integer, default=0, nullable=False)
    ima_sync_enabled = Column(Boolean, default=False, nullable=False)
    ima_use_default_account = Column(Boolean, default=True, nullable=False)
    ima_account_id = Column(Integer, ForeignKey("ima_accounts.id", ondelete="SET NULL"), nullable=True)
    ima_use_default_target = Column(Boolean, default=True, nullable=False)
    ima_target_type = Column(String(32), nullable=True)
    ima_note_folder_id = Column(String(255), nullable=True)
    ima_note_folder_name = Column(String(255), nullable=True)
    ima_knowledge_base_id = Column(String(255), nullable=True)
    ima_knowledge_base_name = Column(String(255), nullable=True)
    ima_knowledge_folder_id = Column(String(255), nullable=True)
    ima_knowledge_folder_name = Column(String(255), nullable=True)
    weekly_period = Column(String(20), nullable=True)
    weekly_start_day = Column(Integer, nullable=True)
    weekly_start_time = Column(String(5), nullable=True)
    weekly_end_day = Column(Integer, nullable=True)
    weekly_end_time = Column(String(5), nullable=True)
    topic_text_layout = Column(String(20), nullable=False, default="per_topic")
    topic_text_merge_threshold = Column(Integer, nullable=False, default=3)
    topic_image_enabled = Column(Boolean, default=False, nullable=False)
    topic_image_layout = Column(String(20), nullable=False, default="single")
    topic_image_merge_threshold = Column(Integer, nullable=False, default=3)
    topic_image_backup_enabled = Column(Boolean, default=False, nullable=False)
    topic_image_backup_path = Column(Text, nullable=True)
    image_prompt_template_id = Column(Integer, ForeignKey("prompt_templates.id", ondelete="SET NULL"), nullable=True)
    image_prompt = Column(Text, nullable=True)
    image_split_enabled = Column(Boolean, default=False, nullable=False)
    image_split_prompt = Column(Text, nullable=True)
    image_aspect_ratio = Column(String(20), nullable=False, default="auto")
    image_resolution = Column(String(10), nullable=False, default="auto")
    max_image_count = Column(Integer, nullable=False, default=6)
    card_renderer = Column(String(10), nullable=False, default="ai")
    card_font_theme = Column(String(10), nullable=False, default="A")

    task = relationship("Task", back_populates="jobs")
    executions = relationship("Execution", back_populates="job", cascade="all, delete-orphan")
    github_config = relationship("GithubConfig", back_populates="jobs", foreign_keys=[github_config_id])
    message_stats_github_config = relationship("GithubConfig", foreign_keys=[message_stats_github_config_id])
    ima_account = relationship("ImaAccount", foreign_keys=[ima_account_id])
    image_prompt_template = relationship("PromptTemplate", foreign_keys=[image_prompt_template_id])

    @property
    def ima_account_name(self) -> Optional[str]:
        return self.ima_account.name if self.ima_account else None
