"""baseline: current schema

Revision ID: e5b78ba646f6
Revises: 
Create Date: 2026-09-09 13:16:41.316647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b78ba646f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_record_settings',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('chatlog_base_url', sa.Text(), nullable=False),
    sa.Column('chatlog_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('chatlog_decrypt_before_fetch', sa.Boolean(), nullable=False),
    sa.Column('chatlog_decrypt_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('chatlog_decrypt_cache_enabled', sa.Boolean(), nullable=False),
    sa.Column('chatlog_decrypt_cache_buffer_sec', sa.Integer(), nullable=False),
    sa.Column('chatlog_work_dir', sa.Text(), nullable=False),
    sa.Column('weflow_base_url', sa.Text(), nullable=False),
    sa.Column('weflow_token_cipher', sa.Text(), nullable=True),
    sa.Column('weflow_page_limit', sa.Integer(), nullable=False),
    sa.Column('weflow_page_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('weflow_empty_page_retry', sa.Integer(), nullable=False),
    sa.Column('weflow_include_media', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_record_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_record_settings_id'), ['id'], unique=False)

    op.create_table('disk_inspection_jobs',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(length=30), nullable=False),
    sa.Column('schedule_time', sa.String(length=5), nullable=False),
    sa.Column('schedule_weekday', sa.Integer(), nullable=True),
    sa.Column('schedule_month_day', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sa.String(length=120), nullable=True),
    sa.Column('interval_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.String(length=5), nullable=False),
    sa.Column('window_end', sa.String(length=5), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('threshold_bytes', sa.Integer(), nullable=False),
    sa.Column('webhook_ids', sa.Text(), nullable=False),
    sa.Column('cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('weflow_process_names', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disk_inspection_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disk_inspection_jobs_id'), ['id'], unique=False)

    op.create_table('github_configs',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('repo', sa.String(length=120), nullable=False),
    sa.Column('branch', sa.String(length=80), nullable=False),
    sa.Column('path_prefix', sa.String(length=255), nullable=True),
    sa.Column('filename_template', sa.String(length=255), nullable=False),
    sa.Column('token_cipher', sa.Text(), nullable=False),
    sa.Column('pages_base_url', sa.String(length=255), nullable=True),
    sa.Column('view_url_mode', sa.String(length=40), nullable=False),
    sa.Column('view_url_template', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('github_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_configs_id'), ['id'], unique=False)

    op.create_table('ima_accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('api_key_cipher', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('default_target_type', sa.String(length=32), nullable=False),
    sa.Column('default_note_folder_id', sa.String(length=255), nullable=True),
    sa.Column('default_note_folder_name', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_base_id', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_base_name', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_folder_id', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_folder_name', sa.String(length=255), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=32), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ima_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ima_accounts_id'), ['id'], unique=False)

    op.create_table('models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key_cipher', sa.Text(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('request_standard', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_id'), ['id'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('image_split_enabled', sa.Boolean(), nullable=False),
    sa.Column('image_split_prompt', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_id'), ['id'], unique=False)

    op.create_table('webhooks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url_cipher', sa.Text(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('card_mode', sa.String(length=20), nullable=False),
    sa.Column('card_header_enabled', sa.Boolean(), nullable=False),
    sa.Column('card_header_title', sa.Text(), nullable=True),
    sa.Column('card_header_subtitle', sa.Text(), nullable=True),
    sa.Column('card_header_color', sa.String(length=20), nullable=True),
    sa.Column('image_render_engine', sa.String(length=20), nullable=False),
    sa.Column('feishu_app_id', sa.String(length=120), nullable=True),
    sa.Column('feishu_app_secret_cipher', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_id'), ['id'], unique=False)

    op.create_table('disk_inspection_runs',
    sa.Column('inspection_job_id', sa.Integer(), nullable=True),
    sa.Column('inspection_job_name', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('inspected_at', sa.DateTime(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('threshold_bytes', sa.Integer(), nullable=False),
    sa.Column('total_write_bytes', sa.Integer(), nullable=False),
    sa.Column('total_read_bytes', sa.Integer(), nullable=False),
    sa.Column('max_single_write_bytes', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('chatlog_decrypt_count', sa.Integer(), nullable=False),
    sa.Column('weflow_media_count', sa.Integer(), nullable=False),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.Column('alert_error', sa.Text(), nullable=True),
    sa.Column('webhook_ids', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_job_id'], ['disk_inspection_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disk_inspection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disk_inspection_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disk_inspection_runs_inspection_job_id'), ['inspection_job_id'], unique=False)

    op.create_table('ima_sync_jobs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('ima_account_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('note_folder_id', sa.String(length=255), nullable=True),
    sa.Column('note_folder_name', sa.String(length=255), nullable=True),
    sa.Column('knowledge_base_id', sa.String(length=255), nullable=True),
    sa.Column('knowledge_base_name', sa.String(length=255), nullable=True),
    sa.Column('knowledge_folder_id', sa.String(length=255), nullable=True),
    sa.Column('knowledge_folder_name', sa.String(length=255), nullable=True),
    sa.Column('local_sync_path', sa.Text(), nullable=False),
    sa.Column('recursive_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_extensions', sa.Text(), nullable=True),
    sa.Column('schedule_frequency', sa.String(length=16), nullable=False),
    sa.Column('schedule_weekday', sa.Integer(), nullable=True),
    sa.Column('schedule_time', sa.String(length=5), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_sync_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ima_account_id'], ['ima_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ima_sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ima_sync_jobs_id'), ['id'], unique=False)

    op.create_table('ima_sync_settings',
    sa.Column('default_account_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('api_key_cipher', sa.Text(), nullable=True),
    sa.Column('default_target_type', sa.String(length=32), nullable=False),
    sa.Column('default_note_folder_id', sa.String(length=255), nullable=True),
    sa.Column('default_note_folder_name', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_base_id', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_base_name', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_folder_id', sa.String(length=255), nullable=True),
    sa.Column('default_knowledge_folder_name', sa.String(length=255), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_sync_frequency', sa.String(length=16), nullable=False),
    sa.Column('auto_sync_weekday', sa.Integer(), nullable=True),
    sa.Column('auto_sync_time', sa.String(length=5), nullable=False),
    sa.Column('local_sync_path', sa.Text(), nullable=True),
    sa.Column('recursive_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_extensions', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=32), nullable=True),
    sa.Column('last_sync_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_account_id'], ['ima_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ima_sync_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ima_sync_settings_id'), ['id'], unique=False)

    op.create_table('tasks',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('image_model_id', sa.Integer(), nullable=True),
    sa.Column('image_model_sequence', sa.Text(), nullable=True),
    sa.Column('image_split_enabled', sa.Boolean(), nullable=False),
    sa.Column('image_split_prompt', sa.Text(), nullable=True),
    sa.Column('model_sequence', sa.Text(), nullable=True),
    sa.Column('upstream_task_id', sa.Integer(), nullable=True),
    sa.Column('card_input_source', sa.Text(), nullable=False),
    sa.Column('prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('talkers', sa.Text(), nullable=False),
    sa.Column('talker_names', sa.Text(), nullable=True),
    sa.Column('push_webhook_ids', sa.Text(), nullable=False),
    sa.Column('alert_webhook_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('store_local_results', sa.Boolean(), nullable=False),
    sa.Column('store_chatlog', sa.Boolean(), nullable=False),
    sa.Column('system_prompt_custom_enabled', sa.Boolean(), nullable=False),
    sa.Column('system_prompt_template', sa.Text(), nullable=True),
    sa.Column('system_prompt_include_message_count', sa.Boolean(), nullable=False),
    sa.Column('topic_style_config', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)

    op.create_table('jobs',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('date_baseline', sa.String(length=20), nullable=False),
    sa.Column('schedule_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=True),
    sa.Column('weekdays', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.String(length=5), nullable=True),
    sa.Column('offset_minutes', sa.Integer(), nullable=False),
    sa.Column('interval_enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.String(length=5), nullable=False),
    sa.Column('window_end', sa.String(length=5), nullable=False),
    sa.Column('disk_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('disk_alert_threshold_bytes', sa.Integer(), nullable=False),
    sa.Column('max_retry', sa.Integer(), nullable=False),
    sa.Column('retry_interval_sec', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('github_deploy_enabled', sa.Boolean(), nullable=False),
    sa.Column('github_config_id', sa.Integer(), nullable=True),
    sa.Column('html_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('html_backup_path', sa.Text(), nullable=True),
    sa.Column('html_backup_filename_template', sa.Text(), nullable=True),
    sa.Column('html_backup_filename_date_offset_days', sa.Integer(), nullable=False),
    sa.Column('github_filename_template', sa.Text(), nullable=True),
    sa.Column('days_offset', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('message_stats_enabled', sa.Boolean(), nullable=False),
    sa.Column('message_stats_formats', sa.Text(), nullable=True),
    sa.Column('message_stats_path', sa.Text(), nullable=True),
    sa.Column('message_stats_filename_template', sa.Text(), nullable=True),
    sa.Column('message_stats_filename_date_offset_days', sa.Integer(), nullable=False),
    sa.Column('message_stats_github_enabled', sa.Boolean(), nullable=False),
    sa.Column('message_stats_github_config_id', sa.Integer(), nullable=True),
    sa.Column('message_stats_github_filename_template', sa.Text(), nullable=True),
    sa.Column('message_stats_github_filename_date_offset_days', sa.Integer(), nullable=False),
    sa.Column('message_stats_github_root', sa.Text(), nullable=True),
    sa.Column('chatlog_backup_enabled', sa.Boolean(), nullable=True),
    sa.Column('chatlog_backup_path', sa.Text(), nullable=True),
    sa.Column('chatlog_backup_formats', sa.Text(), nullable=True),
    sa.Column('chatlog_backup_filename_template', sa.Text(), nullable=True),
    sa.Column('chatlog_backup_filename_date_offset_days', sa.Integer(), nullable=False),
    sa.Column('model_output_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('model_output_path', sa.Text(), nullable=True),
    sa.Column('model_output_format', sa.Text(), nullable=True),
    sa.Column('model_output_filename_template', sa.Text(), nullable=True),
    sa.Column('model_output_filename_date_offset_days', sa.Integer(), nullable=False),
    sa.Column('ima_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('ima_use_default_account', sa.Boolean(), nullable=False),
    sa.Column('ima_account_id', sa.Integer(), nullable=True),
    sa.Column('ima_use_default_target', sa.Boolean(), nullable=False),
    sa.Column('ima_target_type', sa.String(length=32), nullable=True),
    sa.Column('ima_note_folder_id', sa.String(length=255), nullable=True),
    sa.Column('ima_note_folder_name', sa.String(length=255), nullable=True),
    sa.Column('ima_knowledge_base_id', sa.String(length=255), nullable=True),
    sa.Column('ima_knowledge_base_name', sa.String(length=255), nullable=True),
    sa.Column('ima_knowledge_folder_id', sa.String(length=255), nullable=True),
    sa.Column('ima_knowledge_folder_name', sa.String(length=255), nullable=True),
    sa.Column('weekly_period', sa.String(length=20), nullable=True),
    sa.Column('weekly_start_day', sa.Integer(), nullable=True),
    sa.Column('weekly_start_time', sa.String(length=5), nullable=True),
    sa.Column('weekly_end_day', sa.Integer(), nullable=True),
    sa.Column('weekly_end_time', sa.String(length=5), nullable=True),
    sa.Column('topic_text_layout', sa.String(length=20), nullable=False),
    sa.Column('topic_text_merge_threshold', sa.Integer(), nullable=False),
    sa.Column('topic_image_enabled', sa.Boolean(), nullable=False),
    sa.Column('topic_image_layout', sa.String(length=20), nullable=False),
    sa.Column('topic_image_merge_threshold', sa.Integer(), nullable=False),
    sa.Column('topic_image_backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('topic_image_backup_path', sa.Text(), nullable=True),
    sa.Column('image_prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('image_split_enabled', sa.Boolean(), nullable=False),
    sa.Column('image_split_prompt', sa.Text(), nullable=True),
    sa.Column('image_aspect_ratio', sa.String(length=20), nullable=False),
    sa.Column('image_resolution', sa.String(length=10), nullable=False),
    sa.Column('max_image_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['github_config_id'], ['github_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ima_account_id'], ['ima_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_stats_github_config_id'], ['github_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)

    op.create_table('executions',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_chars', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_model_name', sa.String(length=120), nullable=True),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('summary_path', sa.Text(), nullable=True),
    sa.Column('chatlog_path', sa.Text(), nullable=True),
    sa.Column('html_backup_path', sa.Text(), nullable=True),
    sa.Column('deploy_status', sa.String(length=20), nullable=False),
    sa.Column('deploy_url', sa.Text(), nullable=True),
    sa.Column('deploy_error', sa.Text(), nullable=True),
    sa.Column('github_config_id', sa.Integer(), nullable=True),
    sa.Column('ima_sync_status', sa.String(length=20), nullable=False),
    sa.Column('ima_sync_error', sa.Text(), nullable=True),
    sa.Column('ima_sync_batch_id', sa.String(length=64), nullable=True),
    sa.Column('raw_request', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('prompt_usage', sa.Text(), nullable=True),
    sa.Column('exported_files', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['github_config_id'], ['github_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_executions_id'), ['id'], unique=False)

    op.create_table('alerts',
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)

    op.create_table('disk_io_records',
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.Text(), nullable=True),
    sa.Column('job_name', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('backend_read_bytes', sa.Integer(), nullable=True),
    sa.Column('backend_write_bytes', sa.Integer(), nullable=True),
    sa.Column('weflow_read_bytes', sa.Integer(), nullable=True),
    sa.Column('weflow_write_bytes', sa.Integer(), nullable=True),
    sa.Column('weflow_captured', sa.Boolean(), nullable=False),
    sa.Column('weflow_process', sa.Text(), nullable=True),
    sa.Column('exported_file_bytes', sa.Integer(), nullable=False),
    sa.Column('chatlog_decrypt_write_bytes', sa.Integer(), nullable=False),
    sa.Column('chatlog_decrypt_status', sa.String(length=20), nullable=True),
    sa.Column('chatlog_work_dir', sa.Text(), nullable=True),
    sa.Column('disk_write_bytes', sa.Integer(), nullable=False),
    sa.Column('total_read_bytes', sa.Integer(), nullable=False),
    sa.Column('total_write_bytes', sa.Integer(), nullable=False),
    sa.Column('job_alert_threshold_bytes', sa.Integer(), nullable=False),
    sa.Column('job_alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('job_alert_sent', sa.Boolean(), nullable=False),
    sa.Column('job_alert_error', sa.Text(), nullable=True),
    sa.Column('media_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_warning', sa.Boolean(), nullable=False),
    sa.Column('warning_reason', sa.Text(), nullable=True),
    sa.Column('raw_snapshot', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disk_io_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disk_io_records_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disk_io_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disk_io_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disk_io_records_task_id'), ['task_id'], unique=False)

    op.create_table('github_deployments',
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('github_config_id', sa.Integer(), nullable=True),
    sa.Column('job_name', sa.String(length=120), nullable=True),
    sa.Column('task_name', sa.String(length=120), nullable=True),
    sa.Column('config_name', sa.String(length=120), nullable=True),
    sa.Column('artifact_type', sa.String(length=40), nullable=True),
    sa.Column('artifact_label', sa.String(length=120), nullable=True),
    sa.Column('repo_full_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=80), nullable=True),
    sa.Column('repo_path', sa.Text(), nullable=True),
    sa.Column('github_file_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pages_url', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['github_config_id'], ['github_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_deployments_id'), ['id'], unique=False)

    op.create_table('ima_sync_records',
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_size', sa.Integer(), nullable=True),
    sa.Column('source_mtime', sa.DateTime(), nullable=True),
    sa.Column('ima_account_id', sa.Integer(), nullable=True),
    sa.Column('ima_account_name', sa.String(length=255), nullable=True),
    sa.Column('sync_job_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('note_folder_id', sa.String(length=255), nullable=True),
    sa.Column('note_folder_name', sa.String(length=255), nullable=True),
    sa.Column('knowledge_base_id', sa.String(length=255), nullable=True),
    sa.Column('knowledge_base_name', sa.String(length=255), nullable=True),
    sa.Column('knowledge_folder_id', sa.String(length=255), nullable=True),
    sa.Column('knowledge_folder_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skip_reason', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_explanation', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('remote_doc_id', sa.String(length=255), nullable=True),
    sa.Column('remote_media_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ima_account_id'], ['ima_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['ima_sync_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ima_sync_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ima_sync_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ima_sync_records_id'), ['id'], unique=False)

    # ensure_schema 时代手工创建的自定义索引（与存量库保持一致）
    op.create_index("idx_jobs_ima_account_id", "jobs", ["ima_account_id"])
    op.create_index("idx_ima_accounts_is_default", "ima_accounts", ["is_default"])
    op.create_index("idx_ima_sync_jobs_account_id", "ima_sync_jobs", ["ima_account_id"])
    op.create_index("idx_ima_sync_records_batch_id", "ima_sync_records", ["batch_id"])
    op.create_index("idx_ima_sync_records_account_id", "ima_sync_records", ["ima_account_id"])
    op.create_index("idx_ima_sync_records_sync_job_id", "ima_sync_records", ["sync_job_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ima_sync_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ima_sync_records_id'))
        batch_op.drop_index(batch_op.f('ix_ima_sync_records_batch_id'))

    op.drop_table('ima_sync_records')
    with op.batch_alter_table('github_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_deployments_id'))

    op.drop_table('github_deployments')
    with op.batch_alter_table('disk_io_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disk_io_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_disk_io_records_job_id'))
        batch_op.drop_index(batch_op.f('ix_disk_io_records_id'))
        batch_op.drop_index(batch_op.f('ix_disk_io_records_execution_id'))

    op.drop_table('disk_io_records')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_id'))

    op.drop_table('executions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('ima_sync_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ima_sync_settings_id'))

    op.drop_table('ima_sync_settings')
    with op.batch_alter_table('ima_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ima_sync_jobs_id'))

    op.drop_table('ima_sync_jobs')
    with op.batch_alter_table('disk_inspection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disk_inspection_runs_inspection_job_id'))
        batch_op.drop_index(batch_op.f('ix_disk_inspection_runs_id'))

    op.drop_table('disk_inspection_runs')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_id'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_id'))

    op.drop_table('models')
    with op.batch_alter_table('ima_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ima_accounts_id'))

    op.drop_table('ima_accounts')
    with op.batch_alter_table('github_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_configs_id'))

    op.drop_table('github_configs')
    with op.batch_alter_table('disk_inspection_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disk_inspection_jobs_id'))

    op.drop_table('disk_inspection_jobs')
    with op.batch_alter_table('chat_record_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_record_settings_id'))

    op.drop_table('chat_record_settings')
    # ### end Alembic commands ###
